name: Build Windows

on:
  push:
    branches:
      - main # Trigger on push to master branch

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner
    
    steps:        
    - uses: 'actions/checkout@v4'
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller virtualenv

    - name: Run Batch File to Build project
      run: |
        python builder.py
